version: '3'
services:
  sls-add:
    build: ./sls-add
    ports:
    - "3010:3000"
    networks:
    - calculator

  sls-sub:
    build: ./sls-sub
    ports:
    - "3020:3000"
    networks:
    - calculator

networks:
  calculator:
